### ISSUE TITLE
Mini-Profiles don't work in Friends List

### ISSUE THREAD

**Issue by SpunkMurphy** [TiberiumFusion/FixedSteamFriendsUI#1]
Mini-Profiles don't show up when you hover over avatars in the Friends List.

However, they do work in 

Single-User Chat

![image](https://github.com/TiberiumFusion/FixedSteamFriendsUI/assets/55606423/c5be5c5a-610c-4074-9dd9-cf32a6e680b8)

Group Chat

![image](https://github.com/TiberiumFusion/FixedSteamFriendsUI/assets/55606423/57119d7d-9ec5-4bad-9e31-5bb75d2affc6)

**Comment by SpunkMurphy** [comment]
Also thank you very much Tiberium for making this patch.

**Comment by TiberiumFusion** [comment]
For the time being, this is intentional.

This is actually something Valve broke, sometime around the start of 2023 iirc, and they never bothered fixing them. I don't know what they changed specifically, but the miniprofile popup has been broken for the last 10 months. It has to do with how the PWA code tries to do window management interop with the Steam client, but I don't have a copy of the PWA code from late 2022 to compare with because Valve rapidly redacts old versions. Doing an investigation to find out how Valve fucked this one up with limited information will be a time consuming process that I just don't have any time for right now. So I disabled the popup miniprofiles and left it at that. They're not a critical feature and they are annoying so it's an acceptable loss for now.

**Note:** If you resize your friends list to be wider than about 500 px, the miniprofiles on hover will start working again. This is because they are now presented within the PWA webpage itself since it's large enough to display them, instead of trying to use their broken window management interop to create a popup frame in dwm. This is also why they can also work in the actual chat windows as well.

Fixing this is on the roadmap eventually I suppose.

**Comment by TiberiumFusion** [comment]
Patch version [2.0.0](https://github.com/TiberiumFusion/FixedSteamFriendsUI/releases/tag/Release-v2.0.0) has been released, which resolves this issue.

The problem was fixed by Valve sometime between 8200419 and 8601984. I have not bothered investigating how or where. Version 2.0.0 is based on 8601984 and thus includes Valve's fix.
