### ISSUE TITLE
here's how the 3.0.0 version fixed the points shop blackscreen issue

### ISSUE THREAD

**Issue by BURGERxBOY** [TiberiumFusion/FixedSteamFriendsUI#12]
https://github.com/TiberiumFusion/FixedSteamFriendsUI/assets/135216471/3058b184-e5ce-4359-b3e9-9834d876edfa

not exactly at full-on fix, BUT, at least it does function now.
( same error happens in other locations aswell, and just like this instance, clicking the refresh button fixes it, temporarily at least. ).

**Comment by TiberiumFusion** [comment]
What you're experiencing is an issue with the entire Steam website. I'll explain.

When the Steam client loads a webpage, it provides a variety of special features to the webpage. This enables the webpage to control the Steam client and by extension control parts of your computer. For example, the friends list webpage uses this to create and control the chat windows on your desktop.

Sometime between Oct 2023 and Dec 2023, Valve added new special features in a Steam client update that are related to VR devices. I don't know exactly what they are supposed to do, but they allow the Steam website to control your VR device when you browse the Steam website using the Steam client. `SetOverlayInteractionAffordance` is one of those features.

Sometime between Oct 2023 and Dec 2023, Valve updated their entire website to use these new VR features on every single webpage, so that the entire Steam website can control your VR device. And, due to Valve's extreme quantity of wealth and extreme lack of proofreading, testing, or common sense, their webpages always try to use the new VR features, even when they don't exist - which is when you are browsing the Steam website on an older client or with a normal web browser.

Using something which doesn't exist is a fatal error which aborts the webpage scripts. There is a small error handler on the page which produces the "Something went wrong while displaying this content. Refresh" message, when this happens.

This is entirely unrelated to FriendsUI or FixedSteamFriendsUI. This is one screwup of many on Valve's global website network.

Several months after creating this screwup, Valve added a very cheap and half-assed "fix" to their screwup in several choice locations on the Steam website in early 2024. It only fixes the issue when browsing the Steam website on a normal web browser. It fails to do anything when browsing the Steam website on an older Steam client.

FixedSteamFriendsUI includes a [patch](https://github.com/TiberiumFusion/FixedSteamFriendsUI/blob/2db8650a978981090d6fd97a3301ff31c37a1547/SnapshotMaker.TsJsRewriter/Scripts/Patches/Definitions/ShimSteamClientOpenVrSoia.ts) which removes the broken Valve code from the steam-chat.com snapshot included in the patch. This only solves the problem for the webpage loaded in the Friends List. All other webpages loaded in the Steam client are unaffected.

Afaik there is no communication between the Friend List's webpage and the webpages loaded in the main library window (like the store, community, your profile, etc). So updating from FixedSteamFriendsUI v2.0.2 to v3.0.0 should *not* have changed anything regarding the issue shown in your post. If it did, that's interesting and worth noting, but far outside of the scope of this project.
