### ISSUE TITLE
issue still present with things not loading in the steam library, potentially fixable?

### ISSUE THREAD

**Issue by BURGERxBOY** [TiberiumFusion/FixedSteamFriendsUI#13]
https://github.com/TiberiumFusion/FixedSteamFriendsUI/assets/135216471/e62bff6c-f572-417e-8dcc-05f1f311d93c

![what's new bug](https://github.com/TiberiumFusion/FixedSteamFriendsUI/assets/135216471/3443bcf7-7776-4801-86d8-fc5ab815aedc)
these issues have been around for awhile, and given how the update to 3.0.0 semi-fixed the points shop not working, these issues may be fixable aswell.

**Comment by TiberiumFusion** [comment]
I use the May 2023 client and I also experience this problem. It first appeared sometime in mid-late 2023 iirc. I do not know why these images fail to load, but I have noticed it is intermittent and sometimes fixes itself if you restart the Steam client.

This problem is unrelated to FixedSteamFriendsUI.

FixedSteamFriendsUI only exists to fix the broken Friends List since Sept 21 2023 in the half-vgui clients. Fixing the rest of Valve's broken and breaking services is far outside the scope of FixedSteamFriendsUI and is an undertaking not to be underestimated. Fixing just the Friends List alone has already totaled over a hundred hours of gratis labor. The rest of the Steam client and global Steam web network is 1000x larger. I am not interested in spending every waking hour of my life fixing all of a $10,000,000,000 company's fuckups for a wage of $0 and an extremely tiny userbase.

If the image loading problem is important to you, you may have better luck consulting the [millenium](https://github.com/SteamClientHomebrew/Millennium) or [steam friends patcher](https://github.com/PhantomGamers/SFP) projects. These projects concern themselves with modifying a much larger portion of the Steam client experience. They are run by organizations with funding and may be willing to address the image loading problem.
