### ISSUE TITLE
Install Progress log crashing application

### ISSUE THREAD

**Issue by KodoPengin** [TiberiumFusion/FixedSteamFriendsUI#2]
Thanks for the fix, but one issue

After installation and detailed log which files were extracted, try to rightclick, "Copy log to clipboard" let the application crash.

STRG/A/C/V would be an addition to

**Comment by TiberiumFusion** [comment]
> "Copy log to clipboard" let the application crash.

This does not reproduce in my testing.
What language is your system set to? What time zone is your system set to?

> STRG/A/C/V would be an addition to

By "STRG/A/C/V" I am going to assume that's some kind of typo and you are trying to refer to Ctrl A Ctrl C and Ctrl V hotkeys, right? Those would be helpful as a fallback if `Copy log to clipboard` is failing but that shouldn't be failing in the first place. But I need to be able to reproduce the crash in my testing first.

**Comment by TiberiumFusion** [comment]
Closing due to lack of required activity. Will reopen if required activity resumes at a later date.

**Comment by KodoPengin** [comment]
Hello, sorry for the late reply

Yes, i refered to the Ctrl A, Ctrl C and Ctrl V hotkeys.

System was Windows 11 Enterprise 64-Bit (10.0, Build 22621)
Language German, Timezone (UTC+01:00)

---

Well, i updated today to the 1.2.0 version of your Quick Patcher, everything works as it should.

Thanks for your updates and effort

**Comment by TiberiumFusion** [comment]
Thanks for the additional info.

I do not support Bugcrash 11 and it is not a platform I test against. It is possible that Bugcrash is the reason behind the QuickPatcher crash you experienced, rather than your culture and region settings. When I have the time I will try to reproduce the crash with your language and time zone on a supported version of Windows.

> everything works as it should.

Are you saying that "Copy log to clipboard" no longer causes the crash you were previously experiencing? Does the log successfully copy to the clipboard when you click that option? Or does nothing at all happen?

There were some minor changes to the QuickPatcher since 1.0.0 that avoid a potential crash in that area, but the intended action (copying the log to the clipboard) still won't occur, if all other factors remain equal. In other words, clicking that option should do nothing, and the clipboard should remain unchanged.
